name = "zipyy"
account_id = "e816384a08fa80bde19c9b060b1c8c5e"

main = "./.cloudflare/worker.js"
site.bucket = "./.svelte-kit/.cloudflare"

build.command = "bun run build"

workers_dev = true
compatibility_date = "2024-05-05"
